### ISSUE TITLE
No refresh token for admin user. Refresh token is required.

### ISSUE THREAD

**Issue by veledzimovich-iTechArt** [smnenko/article-webapp#13]
I create user for fresh Django app and field RefreshToken is required in Django Admin.
I can't edit Admin user.
![Screen Shot 2021-08-08 at 19 27 53](https://user-images.githubusercontent.com/77264872/128639154-06923af5-ecd3-4370-8d0d-efcf2a9a0a1f.jpg)

**Comment by smnenko** [comment]
PR #15
